In [ ]:
import numpy as np
import sys

sys.setrecursionlimit(100000)

dimension = 5
HUMAN = 0
BOT = 1
END = 2
labmat = np.zeros((dimension, dimension))
mat = np.zeros((dimension, dimension))
newmat2 = np.full((dimension, dimension), 2)

def verify(i, j):
    if (0 < i <= dimension) and (0 < j <= dimension):
        if labmat[(i-1),(j-1)] == 0:
            return i, j
        else:
            i = int(input("Position already taken. Input I value again."))
            j = int(input("Position already taken. Input J value again."))
            return verify(i, j)
    else:
        i = int(input("Incorrect dimension. Input I value again."))
        j = int(input("Incorrect dimension. Input J value again."))
        return verify(i, j)
    
def verifyBot(i, j):
    if labmat[(i-1),(j-1)] == 0:
        return i, j
    else:
        i = np.random.randint(1, dimension)
        j = np.random.randint(1, dimension)
        return verifyBot(i, j)
    
def intelligent():
    choice = np.argwhere(mat == 1)
    options = np.argwhere(labmat == 1)
    free = np.argwhere(labmat == 0)
    free_set = {tuple(x) for x in free}

    if not options.tolist():
        return 1, 1

    for k in range(len(choice)):
        i, j = choice[k]
        if (i+1, j) in free_set:
            return i+2, j+1
        if (i, j+1) in free_set:
            return i+1, j+2
        if i > 0 and (i-1, j) in free_set:
            return i, j+1
        if j > 0 and (i, j-1) in free_set:
            return i+1, j

    i, j = free[np.random.randint(len(free))]
    return i+1, j+1
        
def intelligent2():
    choice = np.argwhere(newmat2 == 1)
    options = np.argwhere(labmat == 1)
    free = np.argwhere(labmat == 0)
    free_set = {tuple(x) for x in free}

    if not options.tolist():
        return 1, 1
    
    zeros = np.argwhere(newmat2 == 0)
    
    if len(zeros) >= 2:
        for row_idx in range(newmat2.shape[0]):
            row_zeros = [(i, j) for i, j in zeros if i == row_idx]
            if len(row_zeros) >= 2:
                for j in range(newmat2.shape[1]):
                    if (row_idx, j) in free_set:
                        return row_idx + 1, j + 1
        
        for col_idx in range(newmat2.shape[1]):
            col_zeros = [(i, j) for i, j in zeros if j == col_idx]
            if len(col_zeros) >= 2:
                for i in range(newmat2.shape[0]):
                    if (i, col_idx) in free_set:
                        return i + 1, col_idx + 1
                    
    for k in range(len(choice)):
        i, j = choice[k]
        if (i+1, j) in free_set:
            return i+2, j+1
        if (i, j+1) in free_set:
            return i+1, j+2
        if i > 0 and (i-1, j) in free_set:
            return i, j+1
        if j > 0 and (i, j-1) in free_set:
            return i+1, j

    i, j = free[np.random.randint(len(free))]
    return i+1, j+1
    
def game(player):
    global labmat
    global mat
    if player == 0:
        posi = int(input("Select your chosen i'th coordinate."))
        posj = int(input("Select your chosen j'th coordinate."))
        pos = verify(posi, posj)
        posi = pos[0]
        posj = pos[1]
        posi = posi - 1
        posj = posj - 1
        labmat[posi, posj] = 1
        tot = 0
        for k in range(dimension):
            for l in range(dimension):
                tot = int(tot + mat[k,l])
        if tot == int(dimension*dimension):
            game(END)
        game(BOT)
    if player == 1:
        boti = np.random.randint(1,dimension)
        botj = np.random.randint(1,dimension)
        bot = verifyBot(boti, botj)
        print(f"Bot chose position {bot}")
        boti = bot[0]
        botj = bot[1]
        boti = boti - 1
        botj = botj - 1
        labmat[boti, botj] = 1
        mat[boti, botj] = 1
        print(f"Current Matrix: {mat}")
        print(f"Spaces available: {labmat}")
        tot = 0
        for k in range(dimension):
            for l in range(dimension):
                tot = int(tot + mat[k,l])
        if tot == int(dimension*dimension):
            game(END)
        game(HUMAN)
    if player == 2:
        det = np.linalg.det(mat)
        if det == 0:
            print("You won.")
            return
        else:
            print("Bot won.")
            return
     
    
def verify2(i, j):
    while True:
        if (0 < i <= dimension) and (0 < j <= dimension):
            if labmat[i-1, j-1] == 1:
                return i, j
            else:
                print("Position already taken.")
        else:
            print("Incorrect dimension.")
            
        i = int(input("Input I value again."))
        j = int(input("Input J value again."))
        
    
def verifyBot2():
    free = np.argwhere(labmat == 0)
    if len(free) == 0:
        return None
    i, j = free[np.random.randint(len(free))]
    return i + 1, j + 1
    
def gameRevised():
    player = HUMAN

    while True:
        if player == HUMAN:
            posi = int(input("Select your chosen i'th coordinate."))
            posj = int(input("Select your chosen j'th coordinate."))
            posi, posj = verify(posi, posj)
            posi = posi - 1
            posj = posj - 1
            labmat[posi, posj] = 1
            mat[posi, posj] = 0
            print(f"Current Matrix:\n{mat}")
            player = BOT

        elif player == BOT:
            boti, botj = verifyBot2()
            print(f"Bot chose position {(boti, botj)}")
            boti = boti - 1
            botj = botj - 1
            labmat[boti, botj] = 1
            mat[boti, botj] = 1
            print(f"Current Matrix:\n{mat}")
            print(f"Availibility Matrix:\n{labmat}")
            player = HUMAN

        if np.sum(labmat) == (dimension*dimension):
            break

    det = np.linalg.det(mat)
    if det == 0:
        print("You won.")
    else:
        print("Bot won.")
        
#gameRevised()

def gameInt():
    player = HUMAN

    while True:
        if player == HUMAN:
            posi = int(input("Select your chosen i'th coordinate."))
            posj = int(input("Select your chosen j'th coordinate."))
            posi, posj = verify(posi, posj)
            posi = posi - 1
            posj = posj - 1
            labmat[posi, posj] = 1
            mat[posi, posj] = 0
            print(f"Current Matrix:\n{mat}")
            player = BOT

        elif player == BOT:
            boti, botj = intelligent()
            print(f"Bot chose position {(boti, botj)}")
            boti = boti - 1
            botj = botj - 1
            labmat[boti, botj] = 1
            mat[boti, botj] = 1
            print(f"Current Matrix:\n{mat}")
            print(f"Availibility Matrix:\n{labmat}")
            player = HUMAN

        if np.sum(labmat) == (dimension*dimension):
            break

    det = np.linalg.det(mat)
    if det == 0:
        print("You won.")
    else:
        print("Bot won.")

def gameInt2():
    player = HUMAN
    
    while True:
        if player == HUMAN:
            posi = int(input("Select your chosen i'th coordinate."))
            posj = int(input("Select your chosen j'th coordinate."))
            posi, posj = verify(posi, posj)
            posi = posi - 1
            posj = posj - 1
            labmat[posi, posj] = 1
            newmat2[posi, posj] = 0
            print(f"Current Matrix:\n{newmat2}")
            player = BOT

        elif player == BOT:
            boti, botj = intelligent2()
            print(f"Bot chose position {(boti, botj)}")
            boti = boti - 1
            botj = botj - 1
            labmat[boti, botj] = 1
            newmat2[boti, botj] = 1
            print(f"Current Matrix:\n{newmat2}")
            print(f"Availibility Matrix:\n{labmat}")
            player = HUMAN

        if np.sum(labmat) == (dimension*dimension):
            break

    det = np.linalg.det(newmat2)
    if det == 0:
        print("You won.")
    else:
        print("Bot won.")  
        
#gameInt()
gameInt2()
        
def testmat():
    newmat = np.zeros((dimension, dimension))
    n1 = 0
    dimsquare = int(dimension * dimension)
    
    if (dimsquare % 2) == 0:
        n1 = int(dimsquare / 2)
    else:
        dim = dimsquare - 1
        n1 = int(dim / 2)
    
    for k in range(n1):
        free = np.argwhere(newmat == 0)
        i, j = free[np.random.randint(len(free))]
        newmat[i, j] = 1
    
    return newmat, np.linalg.det(newmat)

testlist = []
commons = []
commonarr = np.zeros((dimension, dimension))

for l in range(1000):
    tester = testmat()
    if tester[1] == 0:
        commons = commons + [tester[0]]
    testlist = testlist + [tester]
    
for l in range(len(commons)):
    commonarr += commons[l]
    
#print(testlist)
over300 = np.argwhere(commonarr >= 300)
mat300 = np.zeros((dimension, dimension))
for k in range(len(over300)):
    i, j = over300[k]
    mat300[i, j] = 1

def highestNum(trix):
    dimsquare = int(dimension*dimension)
    even = int(dimsquare/2)
    odd = int((dimsquare - 1)/2)
    sort = np.sort(trix, axis=None)
    highest 
    if dimsquare % 2 == 0:
        for k in range(even):
            highest += [sort[k+even]]
    else:
        for k in range(odd):
            highest += [sort[k+1+odd]]
    return 3

# higestNum function unfinished, due to realisation of its pointlessness

#print(commonarr)
#print(over300)
print(commonarr)
print(mat300)
#testmat()

Select your chosen i'th coordinate. 1
Select your chosen j'th coordinate. 1


Current Matrix:
[[0 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Bot chose position (1, 3)
Current Matrix:
[[0 2 1 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Availibility Matrix:
[[1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Select your chosen i'th coordinate. 3
Select your chosen j'th coordinate. 3


Current Matrix:
[[0 2 1 2 2]
 [2 2 2 2 2]
 [2 2 0 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Bot chose position (2, 3)
Current Matrix:
[[0 2 1 2 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Availibility Matrix:
[[1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Select your chosen i'th coordinate. 5
Select your chosen j'th coordinate. 5


Current Matrix:
[[0 2 1 2 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 2]
 [2 2 2 2 0]]
Bot chose position (1, 4)
Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 2]
 [2 2 2 2 0]]
Availibility Matrix:
[[1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


Select your chosen i'th coordinate. 5
Select your chosen j'th coordinate. 1


Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 2]
 [0 2 2 2 0]]
Bot chose position (5, 2)
Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 2]
 [0 1 2 2 0]]
Availibility Matrix:
[[1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1.]]


Select your chosen i'th coordinate. 4
Select your chosen j'th coordinate. 5


Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 0]
 [0 1 2 2 0]]
Bot chose position (5, 3)
Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [2 2 0 2 2]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Availibility Matrix:
[[1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1.]]


Select your chosen i'th coordinate. 3
Select your chosen j'th coordinate. 5


Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [2 2 0 2 0]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Bot chose position (3, 1)
Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 2]
 [1 2 0 2 0]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Availibility Matrix:
[[1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1.]]


Select your chosen i'th coordinate. 2
Select your chosen j'th coordinate. 5


Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 0]
 [1 2 0 2 0]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Bot chose position (3, 2)
Current Matrix:
[[0 2 1 1 2]
 [2 2 1 2 0]
 [1 1 0 2 0]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Availibility Matrix:
[[1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1.]]


Select your chosen i'th coordinate. 1
Select your chosen j'th coordinate. 5


Current Matrix:
[[0 2 1 1 0]
 [2 2 1 2 0]
 [1 1 0 2 0]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Bot chose position (1, 2)
Current Matrix:
[[0 1 1 1 0]
 [2 2 1 2 0]
 [1 1 0 2 0]
 [2 2 2 2 0]
 [0 1 1 2 0]]
Availibility Matrix:
[[1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1.]]
